name: doslownie
description: Wordle clone

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  get_it: ^7.2.0

  cupertino_icons: ^1.0.2
  material_color_utilities: ^0.1.4
  dynamic_color: ^1.1.2
  another_flushbar: ^1.10.28
  expand_tap_area: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/pl-PL.db
    - assets/en-US.db
