name: doslownie
description: Your unlimited word game

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^9.1.1
  equatable: ^2.0.3
  get_it: ^8.0.3
  intl: ^0.20.2

  cupertino_icons: ^1.0.2
  material_color_utilities: 0.11.1
  dynamic_color: ^1.3.0
  another_flushbar: ^1.10.28
  expand_tap_area: ^1.1.0
  flutter_svg: ^2.2.0
  sizer: ^3.0.5
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 22 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#db517c"
    theme_color: "#6767df"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Coiny
      fonts:
        - asset: assets/fonts/Coiny-Regular.ttf

  assets:
    - assets/icons/Logotype.png
    - assets/icons/icon.png
    - assets/icons/full_logo.svg
    - i18n/en_US.json
    - i18n/pl_PL.json
    - assets/pl-PL_extended.db
    - assets/en-US_extended.db
    - assets/pl-PL.db
    - assets/en-US.db
