name: doslownie
description: Your unlimited word game

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  get_it: ^7.2.0
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  material_color_utilities: ^0.1.4
  dynamic_color: ^1.1.2
  another_flushbar: ^1.10.28
  expand_tap_area: ^1.1.0
  flutter_svg: ^1.0.3
  flutter_launcher_icons:
    git: https://github.com/dirkbo/flutter_launcher_icons.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  windows: true
  web: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/icon.svg
    - i18n/en_US.json
    - i18n/pl_PL.json
    - assets/pl-PL.db
    - assets/en-US.db
    - assets/riddle-pl-PL.db
    - assets/riddle-en-US.db
